# This file is used to generate config.base, which the shell scripts
# process before any other files.  The config.base sets global
# variables and default values that are needed throughout the
# scripting system.

config_base:
  filename: config.base
  content: !expand |
    #!/bin/ksh -x
    
    ########## config.base ##########
    # Common to all steps
    
    echo "BEGIN: config.base"
    
    # Machine environment
    export machine="{doc.platform.name}"
    
    # EMC parallel or NCO production
    export RUN_ENVIR="emc"
    
    # Account, queue, etc.
    export ACCOUNT="{doc.accounting.cpu_project}"
    export QUEUE="{doc.platform.exclusive_queue}"
    export QUEUE_ARCH="{doc.platform.service_queue}"
        
    # Project to use in mass store:
    HPSS_PROJECT={doc.accounting.hpss_project}
    
    # Directories relative to installation areas:
    export HOMEgfs="{doc.places.HOMEgfs}"
    export PARMgfs=$HOMEgfs/parm
    export FIXgfs=$HOMEgfs/fix
    export USHgfs=$HOMEgfs/ush
    export UTILgfs=$HOMEgfs/util
    export EXECgfs=$HOMEgfs/exec
    export SCRgfs=$HOMEgfs/scripts
    
    ########################################################################
    
    # GLOBAL static environment parameters
    export NWPROD="{doc.places.NWPROD}"
    export DMPDIR="{doc.places.DMPDIR}"
    export RTMFIX="{doc.places.RTMFIX}"
    
    export HOMEDIR="{doc.places.HOMEDIR}"
    export STMP="{doc.places.SHORT_TERM_TEMP}/$USER"
    export PTMP="{doc.places.LONG_TERM_TEMP}/$USER"
    export NOSCRUB="{doc.places.NOSCRUB}"
    
    # Base directories for various builds
    export BASE_GIT="{doc.places.BASE_GIT}"
    export BASE_SVN="{doc.places.BASE_SVN}"
    
    # Utilities needed in the scripts (mostly post)
    {doc.platform.config_base_extras}

    # Toggle to turn on/off GFS downstream processing.
    export DO_BUFRSND="{tools.YES_NO(doc.downstream.DO_BUFRSND)}" # Run GFS_POSTSND
    export DO_GEMPAK="{tools.YES_NO(doc.downstream.DO_GEMPAK)}"  # Run GFS GEMPAK
    export DO_AWIPS="{tools.YES_NO(doc.downstream.DO_AWIPS)}"   # Run GFS AWIPS
    
    ####################################################
    # DO NOT ADD MACHINE DEPENDENT STUFF BELOW THIS LINE
    # IF YOU HAVE TO MAKE MACHINE SPECIFIC CHANGES BELOW
    # FEEL FREE TO MOVE THEM ABOVE THIS LINE TO KEEP IT
    # CLEAR
    ####################################################
    # Build paths relative to $HOMEgfs
    export HOMEgsi="$HOMEgfs"
    export FIXgsi="{doc.places.get('FIXgsi','$HOMEgfs/fix/fix_gsi')}"
    export HOMEfv3gfs="{doc.places.get('HOMEfv3gfs','$HOMEgfs/sorc/fv3gfs.fd')}"
    export HOMEpost="{doc.places.get('HOMEpost','$HOMEgfs')}"
    export HOMEobsproc_prep="{doc.places.get('HOMEobsproc_prep', '$BASE_GIT/obsproc/obsproc_prep.iss-46886.fv3gfs')}"
    export HOMEobsproc_network="{doc.places.get('HOMEobsproc_network', '$BASE_GIT/obsproc/obsproc_global.iss-46886.fv3gfs')}"
    export BASE_VERIF="{doc.places.get('BASE_VERIF', '$BASE_SVN/verif/global/tags/vsdb')}"
    
    # CONVENIENT utility scripts and other environment parameters
    export NCP="/bin/cp -p"
    export NMV="/bin/mv"
    export NLN="/bin/ln -sf"
    export VERBOSE="YES"
    export KEEPDATA="NO"
    export CHGRP_CMD="{doc.platform.CHGRP_RSTPROD_COMMAND}"
    export NEMSIOGET="$HOMEgfs/exec/nemsio_get"
    
    # Machine environment, jobs, and other utility scripts
    export BASE_ENV="$HOMEgfs/env"
    export BASE_JOB="$HOMEgfs/jobs/rocoto"
    
    # EXPERIMENT specific environment parameters
    export SDATE={tools.to_YMDH(doc.settings.SDATE)}
    export EDATE={tools.to_YMDH(doc.settings.EDATE)}
    export REALTIME="{tools.YES_NO(doc.settings.REALTIME)}"   # Run GFS AWIPS
    export assim_freq={doc.data_assimilation.assim_freq}
    export PSLOT="{doc.names.experiment}"
    export EXPDIR="{doc.places.EXPDIR}"
    export ROTDIR="{doc.places.ROTDIR}"
    export RUNDIR="{doc.places.DATAROOT}"
    export ARCDIR="$NOSCRUB/archive/$PSLOT"
    export ICSDIR="{doc.places.ICSDIR}"
    export ATARDIR="/NCEPDEV/$HPSS_PROJECT/1year/$USER/$machine/scratch/$PSLOT"
    
    # Commonly defined parameters in JJOBS
    export envir=${{envir:-"prod"}}
    export NET="gfs"
    export RUN=${{RUN:-${{CDUMP:-"gfs"}}}}
    export jlogfile="${{ROTDIR}}/logs/jlogfile"
    export ERRSCRIPT=${{ERRSCRIPT:-'eval [[ $err = 0 ]]'}}
    export LOGSCRIPT=${{LOGSCRIPT:-""}}
    #export ERRSCRIPT=${{ERRSCRIPT:-"err_chk"}}
    #export LOGSCRIPT=${{LOGSCRIPT:-"startmsg"}}
    export REDOUT="1>"
    export REDERR="2>"
    
    export SENDECF="NO"
    export SENDCOM="NO"
    export SENDDBN="NO"
    export SENDSDM="NO"
    
    # Resolution specific parameters
    export LEVS={doc.fv3_settings.LEVS}
    export CASE="{doc.fv3_settings.CASE}"
    export CASE_ENKF="{doc.fv3_enkf_settings.CASE}"
    
    # Surface cycle update frequency
    export FHCYC={doc.fv3_enkf_settings.FHCYC}
    
    # Output frequency of the forecast model (for cycling)
    export FHMIN={doc.gfs_output_settings.FHMIN_GDAS}
    export FHMAX={doc.gfs_output_settings.FHMAX_GDAS}
    export FHOUT={doc.gfs_output_settings.FHOUT_GDAS}
    
    # GFS cycle info
    export gfs_cyc={doc.settings.gfs_cyc} # 0: no GFS cycle, 1: 00Z only, 2: 00Z and 12Z only, 4: all 4 cycles.
    
    # GFS output and frequency
    export FHMIN_GFS={doc.gfs_output_settings.FHMIN_GFS}
    export FHMAX_GFS={doc.gfs_output_settings.FHMAX_GFS}
    export FHOUT_GFS={doc.gfs_output_settings.FHOUT_GFS}
    export FHMAX_HF_GFS={doc.gfs_output_settings.FHMAX_HF_GFS}
    export FHOUT_HF_GFS={doc.gfs_output_settings.FHOUT_HF_GFS}
    
    # I/O QUILTING, true--use Write Component; false--use GFDL FMS
    # if quilting=true, choose OUTPUT_GRID as cubed_sphere_grid in netcdf or gaussian_grid
    # if gaussian_grid, set OUTPUT_FILE for nemsio or netcdf
    export QUILTING="{tools.fort(doc.fv3_settings.QUILTING)}"
    export OUTPUT_GRID="{doc.gfs_output_settings.OUTPUT_GRID}"
    export OUTPUT_FILE="{doc.gfs_output_settings.OUTPUT_FILE_TYPE}"
    
    # Microphysics Options: 99-ZhaoCarr, 8-Thompson; 6-WSM6, 10-MG, 11-GFDL
    export imp_physics=11
    
    # Shared parameters
    # Hybrid related
    export DOHYBVAR="{tools.YES_NO(doc.data_assimilation.DOHYBVAR)}"
    export NMEM_ENKF={doc.data_assimilation.NMEM_ENKF}
    export SMOOTH_ENKF="{tools.YES_NO(doc.data_assimilation.SMOOTH_ENKF)}"
    export l4densvar="{tools.fort(doc.data_assimilation.l4densvar)}"
    export lwrite4danl=".false."
    
    # EnKF output frequency
    if [ $DOHYBVAR = "YES" ]; then
        export FHMIN_ENKF=3
        export FHMAX_ENKF=9
        if [ $l4densvar = ".true." ]; then
            export FHOUT=1
            export FHOUT_ENKF=1
        else
            export FHOUT_ENKF=3
        fi
    fi
    
    # If YES, NSST is turned on in anal and/or fcst steps
    export DONST="{tools.YES_NO(doc.fv3_settings.DONST)}"
    
    # The switch to apply SST elevation correction or not
    export nst_anl={tools.fort(doc.fv3_settings.nst_anl)}
    
    # Analysis increments to zero in CALCINCEXEC
    export INCREMENTS_TO_ZERO="{tools.join(doc.data_assimilation.INCREMENTS_TO_ZERO,',')}"

    # Archiving options
    export HPSSARCH={tools.YES_NO(doc.archiving.archive_to_hpss)}   # save data to HPSS archive
    export ARCH_CYC={doc.archiving.arch_cyc}           # Archive data at this cycle for warm_start capability. Cannot be 00
    export ARCH_WARMICFREQ={doc.archiving.arch_warmicfreq}     # Archive frequency in days for warm_start capability
    export ARCH_FCSTICFREQ={doc.archiving.arch_fcsticfreq}     # Archive frequency in days for gdas and gfs forecast-only capability
    
    echo "END: config.base"
    
