# This file is used to generate config.fv3ic, which controls the
# chgres.  That is the program that converts Global Spectral Model
# analysis files to Finite Volume 3 input conditions.

config_fv3ic:
  filename: config.fv3ic
  content: !expand |
    #!/bin/ksh -x
    
    ########## config.fv3ic ##########
    # Convert GFS initial conditions into FV3 initial conditions
    
    echo "BEGIN: config.fv3ic"
    
    # Task and thread configuration
    export wtime_fv3ic="00:30:00"
    export npe_fv3ic={doc.resources.run_fv3ic.total_ranks()}
    export npe_node_fv3ic={doc.resources.run_fv3ic.total_ranks()}
    
    echo "END: config.fv3ic"
    
