settings_schema: !Template &settings_schema

  realtime:
    type: bool
    default: false
    description: "Simulation of an event that is currently happening (ie.: a forecast)"

  four_cycle_mode:
    type: bool
    description: "Enable NCO-like four cycle suite.  Not well tested.  Do not use unless you know what you're doing."
    default: false

  run_gsi:
    type: bool
    description: "Run Gridpoint Statistical Interpolation"

  run_enkf:
    type: bool
    description: "Enable Ensemble Kalman Filter"
    default: !calc run_gsi

  chgres_and_convert_ics: 
    type: bool
    description: "Run the fv3ic job, which changes restart file resolution and converts legacy GFS GSM restart files to FV3 restart files."

  max_job_tries:
    type: int
    default: 1
    description: "Number of times to try running a job.  Set to 1 for no retries."

  IC_CDUMP:
    type: string
    allowed: [ gfs, gdas ]
    optional: true
    description: Get initial conditions from gfs or gdas

  gfs_cyc:
    type: int
    default: 4
    allowed: [ 0, 1, 2, 4 ]
    description: |
      When to run GFS forecast.  Data assimilation is run for every
      cycle regardless of these values
        * 0: no GFS cycle
        * 1: 00Z only
        * 2: 00Z and 12Z only
        * 4: all 4 cycles (0, 6, 12, 18 Z)

  SDATE:
    type: datetime
    description: |
      First cycle to run.  In the cycled workflow, this is a
      "half-cycle" in that it only runs the parts of the workflow that
      do not require a prior cycle.  The first "real" cycle is the
      following cycle.

  EDATE:
    type: datetime
    description: Last cycle to run GDAS.
  
  ics_from:
    type: string
    default: opsgfs
    allowed: [ opsgfs, pargfs ]
    description: initial conditions from opsgfs or pargfs
    if_present: !Template
      parexp: 
        type: string
        default: prnemsrn
      HPSS_PAR_PATH:
        type: string
        default: !expand "/5year/NCEPDEV/emc-global/emc.glopara/WCOSS_C/{parexp}"
