base:
  DO_JEDIATMVAR: "NO"
  DO_JEDIATMENS: "NO"
  DO_JEDIOCNVAR: "NO"
  DO_JEDISNOWDA: "NO"
  DO_MERGENSST: "NO"
  DO_BUFRSND: "NO"
  DO_GEMPAK: "NO"
  DO_AWIPS: "NO"
  KEEPDATA: "NO"
  DO_EXTRACTVARS: "NO"
  FHMAX_GFS: 120
  FHMAX_HF_GFS: 0
  FCST_BREAKPOINTS: "48"
  REPLAY_ICS: "NO"
  USE_OCN_PERTURB_FILES: "false"
  LOCALARCH: "NO"
