base:
  DO_JEDIATMVAR: "NO"
  DO_JEDIATMENS: "NO"
  DO_JEDIOCNVAR: "NO"
  DO_JEDISNOWDA: "NO"
  DO_MERGENSST: "NO"
  DO_BUFRSND: "NO"
  DO_GEMPAK: "NO"
  DO_AWIPS: "NO"
  KEEPDATA: "NO" 
  FHMAX_GFS: 120
  REPLAY_ICS: "NO"

