base:
  DO_JEDIATMVAR: "NO"
  DO_JEDIATMENS: "NO"
  DO_JEDIOCNVAR: "NO"
  DO_JEDISNOWDA: "NO"
  DO_MERGENSST: "NO"
  DO_BUFRSND: "NO"
  DO_GEMPAK: "NO"
  DO_AWIPS: "NO"
  KEEPDATA: "NO"
  DO_EXTRACTVARS: "NO"
  FHMAX_GFS: 2976
  FHMAX_HF_GFS: 0
  FHOUT_HF_GFS: 1
  FHOUT_OCN_GFS: 24
  FHOUT_ICE_GFS: 24
  FCST_BREAKPOINTS: ""
  REPLAY_ICS: "NO"
  HPSSARCH: "NO"
  LOCALARCH: "NO"
fcst:
  TYPE: "hydro"
  MONO: "mono"
  reforecast: "YES"
  FHZER: 12
  POST_SFS: "YES"
stage_ic:
  USE_OCN_ENS_PERTURB_FILES: "YES"
  USE_ATM_ENS_PERTURB_FILES: "YES"
ocn:
  MOM6_INTERP_ICS: "YES"
