name: pynorms
on: [pull_request] # TODO [push, pull_request]

jobs:
  check_norms:
    runs-on: ubuntu-latest
    name: Check Python coding norms with pycodestyle

    steps:

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pycodestyle

    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: global-workflow

    - name: Run pycodestyle
      run: |
        cd $GITHUB_WORKSPACE/global-workflow
        pycodestyle -v --config ./.pycodestyle ./
